// Templates / macros
_items{item, separator}: item (separator item)*

_block: "{" stmt* "}" | stmt

_coord: DOUBLE ~ 3

_angle: DOUBLE ~ 2

_entity_ref: ENTITY_SEL | USERNAME | UUID

// Top level
start: (definition | metadef)*

metadef: "metadef" "namespace" ID ";" -> namespace_metadef

definition: "def" "func" resource_loc "(" _items{ID, ","}? ")" _block -> func_def
          | "def" "tick" resource_loc _block                          -> tick_def
          | "def" "load" resource_loc _block                          -> load_def

stmt: variable "=" expr ";"                       -> assignment
    | resource_loc "(" _items{expr, ","}? ")" ";" -> func_call
    | if_stmt elif_stmt* else_stmt?               -> conditional
    | "repeat" INT _block                         -> repeat
    | "execute" RAW _block                        -> execute
    | RAW ";"                                     -> run

// Parts of a statements
if_stmt: "if" "(" disjunction ")" _block

elif_stmt: "elif" "(" disjunction ")" _block

else_stmt: "else" _block

// Math expressions
?expr: term
     | expr SIGN term

?term: signed_power
     | term MUL_OP signed_power

?signed_power: SIGN* power

?power: group
      | group "^" power

?group: _entity_ref ("." ID)+ -> entity_prop
      | variable
      | "(" expr ")"
      | INT
      | DOUBLE

// Logical expressions
?disjunction: conjunction
            | disjunction "||" conjunction

?conjunction: negation
            | conjunction "&&" negation

?negation: "!" negation -> logic_not
         | "(" disjunction ")"
         | comparison
         | BOOL

comparison: expr COMPARATOR expr  

// Storage
resource_loc: (ID ":")? ID

variable: resource_loc? ID

// ======= TERMINALS =======
USERNAME: /[a-zA-Z0-9_]{3,16}/

UUID: /[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[ab89][a-f0-9]{3}-[a-f0-9]{12}/

ID: /[a-zA-Z_][a-zA-Z0-9_]*/

ENTITY_SEL: /@[spnr]/

RAW.-1: /`[^`]*`/

// Execute arguments
AXES: /(?!.*(.).*\1)[xyz]+/

ANCHOR: /eyes|feet/

// Data types
INT: /[0-9]+/

DOUBLE.1: /[0-9]*\.[0-9]+/

BOOL: /True|False/

// Operators
SIGN: /[+-]/

MUL_OP: /[*\/]/

COMPARATOR: /==|!=|<|>|<=|>=/

// Decorative elements
WHITESPACE: /\s/

COMMENT: /\/{2}.*|\/\*[\s\S]*\*\//

%ignore WHITESPACE
%ignore COMMENT
