// Templates / macros
_items{item, separator}: item (separator item)*

_block: "{" stmt* "}" | stmt

_coord: DOUBLE ~ 3

_angle: DOUBLE ~ 2
aabb
// Top level
start: definition*

definition: "def" "func" ID "(" _items{ID, ","}? ")" _block -> func_def
          | "def" "tick" ID _block                          -> tick_def
          | "def" "load" ID _block                          -> load_def

stmt: ID "=" expr ";"                         -> assignment
    | ID "(" _items{expr, ","}? ")" ";"       -> func_call
    | if_stmt elif_stmt* else_stmt?           -> conditional
    | "repeat" INT _block                     -> repeat
    | "execute" _items{exec_arg, ","} _block  -> execute
    | "run" RAW ";"                           -> run

// Parts of a statements
if_stmt: "if" "(" disjunction ")" _block

elif_stmt: "elif" "(" disjunction ")" _block

else_stmt: "else" _block


exec_arg: "align" AXES                  -> exec_align
        | "anchored" ANCHOR             -> exec_anchor
        | "as" ID                       -> exec_as
        | "at" ID                       -> exec_at
        | "facing" _coord               -> exec_facing
        | "facing" "entity" ENTITY_SEL  -> exec_facing_entity
        | "in" (ID ":")? ID             -> exec_in
        | "on" RELATION                 -> exec_on
        | "positioned" _coord           -> exec_pos
        | "positioned" "as" ENTITY_SEL  -> exec_pos_as
        | "positioned" "over" HEIGHTMAP -> exec_pos_over
        | "rotated" _angle              -> exec_rotated
        | "rotated as" ENTITY_SEL       -> exec_rotated_as
        | "summon" (ID ":")? ID         -> exec_summon

// Math expressions
?expr: term
     | expr SIGN term

?term: signed_power
     | term MUL_OP signed_power

?signed_power: SIGN* power

?power: group
      | group "^" power

?group: ENTITY_SEL ("." ID)+ -> entity_prop
      | "(" expr ")"
      | ID
      | INT
      | DOUBLE

// Logical expressions
?disjunction: conjunction
            | disjunction "||" conjunction

?conjunction: negation
            | conjunction "&&" negation

?negation: "!" negation -> logic_not
         | "(" disjunction ")"
         | comparison
         | BOOL

comparison: expr COMPARATOR expr


// ======= TERMINALS =======
ID: /[a-zA-Z_][a-zA-Z0-9_]*/

ENTITY_SEL: /@[spnr]/

RAW.-1: /[^;]+/

// Execute arguments
AXES: /(?!.*(.).*\1)[xyz]+/

ANCHOR: /eyes|feet/

RELATION: /attacker|controller|leasher|origin|owner|passengers|target|vehicle/

HEIGHTMAP: /world_surface|motion_blocking|motion_blocking_no_leaves|ocean_floor/

// Data types
INT: /[0-9]+/

DOUBLE.1: /[0-9]*\.[0-9]+/

BOOL: /True|False/

// Operators
SIGN: /[+-]/

MUL_OP: /[*\/]/

COMPARATOR: /==|!=|<|>|<=|>=/

// Decorative elements
WHITESPACE: /\s/

COMMENT: /\/{2}.*|\/\*[\s\S]*\*\//

%ignore WHITESPACE
%ignore COMMENT
