name: CI test
on:
  pull_request:
    branches:
      - main

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: 3.14.6
      
      - name: Install dependencies
        run: |
          pip install --break-system-packages lark
          pip install --break-system-packages typer

      - name: Execute program
        run: |
          export PYTHONPATH="${PYTHONPATH}:./src/flintmc"
          pip install -e .
          flintmc test/source_code.flint output/
